### ISSUE TITLE
vpc.add_subnet is not idempotent

### ISSUE THREAD

**Issue by rmt** [yaybu/touchdown#43]
When re-running the same Touchdownfile that contains the following:

> vpc = aws.add_vpc(name='test-vpc', cidr_block='192.168.0.0/22')
> subnet1 = vpc.add_subnet(name='subnet1', cidr_block='192.168.0.1/24')

I receive the error:

> ClientError: An error occurred (InvalidSubnet.Conflict) when calling the CreateSubnet operation: The CIDR '192.168.0.1/24' conflicts with another subnet

**Comment by Jc2k** [comment]
Unfortunately AWS accepts ``192.168.0.1/24`` and normalizes it to ``192.168.0.0/24``. So then touchdown thinks the subnet doesnt exist yet. If you use:

    vpc = aws.add_vpc(name='test-vpc', cidr_block='192.168.0.0/22')
    subnet1 = vpc.add_subnet(name='subnet1', cidr_block='192.168.0.0/24')

it should be ok.

I will probably stop it looking at the cidr_block when setting up a subnet.

**Comment by rmt** [comment]
Thanks. That makes sense. I thought it a bit odd in the example, but then forgot about it. I'd personally normalise it by masking the ip, since I suspect that it's still valid to check the cidr_block.
